FROM ubuntu:20.04 AS build-env

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update \
    && apt-get install -y curl git wget unzip libgconf-2-4 gdb libstdc++6 libglu1-mesa fonts-droid-fallback python3 \
    && apt-get clean

ENV DEBIAN_FRONTEND=dialog
ENV PUB_HOSTED_URL=https://pub.flutter-io.cn
ENV FLUTTER_STORAGE_BASE_URL=https://storage.flutter-io.cn

RUN git clone https://github.com/flutter/flutter.git /usr/local/flutter
ENV PATH="/usr/local/flutter/bin:${PATH}"

RUN flutter channel master \
    && flutter upgrade \
    && flutter config --enable-web

WORKDIR /app/frontend/area

COPY ./app/frontend .

RUN flutter doctor

RUN flutter clean \
    && flutter pub upgrade \
    && flutter pub get \
    && flutter build web

FROM nginx:1.25.2-alpine

COPY --from=build-env /app/frontend/area/build/web /usr/share/nginx/html

EXPOSE 8081

RUN sed -i 's/listen\(.*\)80;/listen\18081;/' /etc/nginx/conf.d/default.conf
RUN sed -i '/location \/ {/a allow all;' /etc/nginx/conf.d/default.conf

RUN sed -i '/location \/ {/a \
location /client.apk { \
  alias /app/frontend/area/build/app/outputs/flutter-apk/client-mobile.apk; \
  default_type application/vnd.android.package-archive; \
  allow all; \
}' /etc/nginx/conf.d/default.conf

CMD ["nginx", "-g", "daemon off;"]