version: '3'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile-backend
    ports:
      - "8080:8080"

  client_mobile:
    build:
      context: .
      dockerfile: Dockerfile-mobile
    depends_on:
      - backend
    volumes:
      - shared-volume:/app/frontend/area/build/app/outputs/flutter-apk

  client-web:
    build:
      context: .
      dockerfile: Dockerfile-web
    ports:
      - "8081:8081"
    depends_on:
      - client_mobile
      - backend
    volumes:
      - shared-volume:/app/frontend/area/build/app/outputs/flutter-apk

volumes:
  shared-volume: